disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Paretile"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "/img/author.jpg"
description = "Hanging out at the intersection of sports, technology, and psychology."

[params.author]
name = "Paretile"
email = "paretile@gmail.com"
headline = "Hanging out at the intersection of sports, technology, and psychology."

links = [
  { x-twitter = "https://x.com/paretile" },
  { github = "https://github.com/paretile" }
]
