disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = ""

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "/img/author.jpg"
description = "Hanging out at the intersection of sports, technology, and psychology."

[params.author]
name = "Paretile"
email = "paretile@gmail.com"
headline = "Hanging out at the intersection of sports, technology, and psychology."

[[params.author.links]]
name = "x-twitter"
url = "https://x.com/paretile"

[[params.author.links]]
name = "github"
url = "https://github.com/paretile"
